version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mem
    versions:
    - 8.0.0
    - 8.1.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: craftcms/cms
    versions:
    - 3.6.1
    - 3.6.10
    - 3.6.11
    - 3.6.11.1
    - 3.6.11.2
    - 3.6.2
    - 3.6.3
    - 3.6.4.1
    - 3.6.5.1
    - 3.6.6
    - 3.6.7
    - 3.6.8
    - 3.6.9
